module github.com/wlt/adblocker

go 1.25.0

// This module is designed for `gomobile bind -target=android -androidapi=21 .`
// to produce an Android .aar from mobile.go. The gomobile tool itself
// brings in golang.org/x/mobile at bind time; mobile.go does not import
// x/mobile directly (the binding glue is generated by gomobile), so we do
// not pin x/mobile here. Run `go install golang.org/x/mobile/cmd/gomobile@latest`
// once on the build host, then `gomobile init` + `gomobile bind` to produce
// wlt.aar.

tool golang.org/x/mobile/cmd/gobind

require (
	golang.org/x/mobile v0.0.0-20260709172247-6129f5bee9d5 // indirect
	golang.org/x/mod v0.38.0 // indirect
	golang.org/x/sync v0.22.0 // indirect
	golang.org/x/tools v0.48.0 // indirect
)
